language: elixir
matrix:
  include:
# TODO: temporarily disabled since the newest version of Hackney (used by excoveralls) doesn't seem to work with OTP 20 ("Compiling src/hackney_ssl.erl failed")
#    - otp_release: 20.0
#      elixir: 1.8
    - otp_release: 21.0
      elixir: 1.8
    - otp_release: 22.0
      elixir: 1.8
# TODO: temporarily disabled since the newest version of Hackney (used by excoveralls) doesn't seem to work with OTP 20 ("Compiling src/hackney_ssl.erl failed")
#    - otp_release: 20.0
#      elixir: 1.9
    - otp_release: 22.0
      elixir: 1.9
    - otp_release: 21.0
      elixir: 1.10
    - otp_release: 22.0
      elixir: 1.10
    - otp_release: 23.0
      elixir: 1.10
sudo: false
after_script:
  - MIX_ENV=docs mix deps.get
script:
  - MIX_ENV=test mix coveralls.travis
  - mix dialyzer
cache:
  directories:
    - priv/plts
