language: elixir
matrix:
  include:
    - otp_release: 21.0
      elixir: 1.6
    - otp_release: 21.0
      elixir: 1.7
    - otp_release: 19.3
      elixir: 1.8
    - otp_release: 20.0
      elixir: 1.8
    - otp_release: 21.0
      elixir: 1.8
sudo: false
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
script:
  - MIX_ENV=test mix coveralls.travis
